config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :gifts
  resources :task_lists
  resources :finances
  resources :children
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :child
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: %i[ show edit update destroy ]

  # GET /finances or /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1 or /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances or /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to finance_url(@finance), notice: "Finance was successfully created." }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1 or /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to finance_url(@finance), notice: "Finance was successfully updated." }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1 or /finances/1.json
  def destroy
    @finance.destroy!

    respond_to do |format|
      format.html { redirect_to finances_url, notice: "Finance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def finance_params
      params.require(:finance).permit(:child_id, :balance, :expenses)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_finance.html.erb
<div id="<%= dom_id finance %>">
  <p>
    <strong>Child:</strong>
    <%= finance.child_id %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= finance.balance %>
  </p>

  <p>
    <strong>Expenses:</strong>
    <%= finance.expenses %>
  </p>

</div>

app/views/finances/_form.html.erb
<%= form_with(model: finance) do |form| %>
  <% if finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :child_id, class: 'form-label' %>
      <%= form.text_field :child_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :balance, class: 'form-label' %>
      <%= form.number_field :balance, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :expenses, class: 'form-label' %>
      <%= form.number_field :expenses, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if finance.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', finance, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if finance.persisted? %>
      <%= link_to "Cancel", finance, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", finances_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Edit Finance</h1>

<%= render 'form', finance: @finance %>

app/views/finances/index.html.erb
<div class="row">
  <div class="col-sm-6">
  <div class="one">
    <h1 id = "Finances">Finances</h1>
    </div>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_finance_path, class: 'btn btn-primary' do %>
    Add New Finance
  <% end %>
  </div>
</div>

<div>
  <table class="content-table">
    <thead>
      <tr class = "active-row">
    

            <th>Child</th>
            <th>Balance</th>
            <th>Expenses</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @finances.each do |finance| %>
        <%= content_tag :tr, id: dom_id(finance), class: dom_class(finance) do %>
          

                      <td><%= finance.child.username %></td>
                      <td><%= finance.balance %></td>
                      <td><%= finance.expenses %></td>
          
          
            <td><%= link_to 'Show', finance %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<img id = "Logo" src = "https://cdn.discordapp.com/attachments/1071114654534860891/1208753249281249321/image.png?ex=65e46e30&is=65d1f930&hm=914efb907392d0fb407f664bc1df4503102fe12c3e6a1e04ecde05e378da2030&">

app/views/finances/new.html.erb
<h1>New finance</h1>

<%= render 'form', finance: @finance %>

app/views/finances/show.html.erb
<div class="page-header">
  <%= link_to finances_path, class: 'btn btn-default' do %>
    All Finances
  <% end %>
  <%= link_to edit_finance_path(@finance), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show finance</h1>
</div>

<dl class="dl-horizontal">
  <dt>Child:</dt>
  <dd><%= @finance.child.username %></dd>
  <dt>Balance:</dt>
  <dd><%= @finance.balance %></dd>
  <dt>Expenses:</dt>
  <dd><%= @finance.expenses %></dd>
</dl>