config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :gifts
  resources :task_lists
  resources :finances
  resources :children
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :child
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: %i[ show edit update destroy ]

  # GET /gifts or /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1 or /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts or /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to gift_url(@gift), notice: "Gift was successfully created." }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1 or /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to gift_url(@gift), notice: "Gift was successfully updated." }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1 or /gifts/1.json
  def destroy
    @gift.destroy!

    respond_to do |format|
      format.html { redirect_to gifts_url, notice: "Gift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gift_params
      params.require(:gift).permit(:child_id, :name, :price)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_with(model: gift) do |form| %>
  <% if gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :child_id, class: 'form-label' %>
      <%= form.text_field :child_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :price, class: 'form-label' %>
      <%= form.number_field :price, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if gift.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', gift, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if gift.persisted? %>
      <%= link_to "Cancel", gift, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", gifts_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/gifts/_gift.html.erb
<div id="<%= dom_id gift %>">
  <p>
    <strong>Child:</strong>
    <%= gift.child_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= gift.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= gift.price %>
  </p>

</div>

app/views/gifts/edit.html.erb
<h1>Edit Gift</h1>

<%= render 'form', gift: @gift %>

app/views/gifts/index.html.erb
 <link rel="stylesheet" href="styles.css" />

<div class="row">
  <div class="col-sm-6">
  <div class = "one">
    <h1 id = "Gift">Gifts</h1>
    </div>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_gift_path, class: 'btn btn-primary' do %>
    Add New Gift
  <% end %>
  </div>
</div>

<div >
  <table class= "content-table">
    <thead>
      <tr class = "active-row">
    
        <th>Name</th>
    

            <th>Child</th>
            <th>Price</th>
            
      </tr>
    </thead>

    <tbody>
      <% @gifts.each do |gift| %>
        <%= content_tag :tr, id: dom_id(gift), class: dom_class(gift) do %>
          
            <td><%= link_to gift.name, gift %></td>
          

                      <td><%= gift.child.username %></td>
                      <td><%= number_to_currency(gift.price)%></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<img id = "Logo" src = "https://cdn.discordapp.com/attachments/1071114654534860891/1208753249281249321/image.png?ex=65e46e30&is=65d1f930&hm=914efb907392d0fb407f664bc1df4503102fe12c3e6a1e04ecde05e378da2030&">

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form', gift: @gift %>

app/views/gifts/show.html.erb
<div class="page-header">
  <%= link_to gifts_path, class: 'btn btn-default' do %>
    All Gifts
  <% end %>
  <%= link_to edit_gift_path(@gift), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show gift</h1>
</div>

<dl class="dl-horizontal">
  <dt>Child:</dt>
  <dd><%= @gift.child.username %></dd>
  <dt>Name:</dt>
  <dd><%= @gift.name %></dd>
  <dt>Price:</dt>
  <dd><%= @gift.price %></dd>
</dl>

<img id = "Logo" src = "https://cdn.discordapp.com/attachments/1071114654534860891/1208753249281249321/image.png?ex=65e46e30&is=65d1f930&hm=914efb907392d0fb407f664bc1df4503102fe12c3e6a1e04ecde05e378da2030&">