config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :gifts
  resources :task_lists
  resources :finances
  resources :children
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/task_list.rb
class TaskList < ApplicationRecord
    belongs_to :child
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: %i[ show edit update destroy ]

  # GET /task_lists or /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1 or /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists or /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to task_list_url(@task_list), notice: "Task list was successfully created." }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1 or /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to task_list_url(@task_list), notice: "Task list was successfully updated." }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1 or /task_lists/1.json
  def destroy
    @task_list.destroy!

    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: "Task list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:child_id, :title, :price, :completed)
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :child_id, class: 'form-label' %>
      <%= form.text_field :child_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :price, class: 'form-label' %>
      <%= form.number_field :price, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if task_list.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', task_list, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if task_list.persisted? %>
      <%= link_to "Cancel", task_list, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", task_lists_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/task_lists/_task_list.html.erb
<div id="<%= dom_id task_list %>">
  <p>
    <strong>Title:</strong>
    <%= task_list.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= task_list.price %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task_list.completed %>
  </p>

</div>

app/views/task_lists/edit.html.erb
<h1>Edit Task_list</h1>

<%= render 'form', task_list: @task_list %>

app/views/task_lists/index.html.erb
<div class="row">
  <div class="col-sm-6">
  <div class = "one">
  
    <h1 id = "Task">Task List</h1>
    </div>
  </div>

  <div class="col-sm-6 text-end">
    <%= link_to 'Add New Task List', new_task_list_path, class: 'btn btn-primary' %>
  </div>
</div>

<div>
  <table class="content-table">
    <thead>
      <tr class = "active-row">
        <th>Child Name</th>
        <th>Title</th>
        <th>Price</th>
        <th>Completed</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @task_lists.each do |task_list| %>
        <tr id="<%= dom_id(task_list) %>" class="<%= dom_class(task_list) %>">
          <td><%= task_list.child.username %></td>
          <td><%= task_list.title %></td>
          <td><%= number_to_currency(task_list.price) %></td>
          <td><%= task_list.completed ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Show', task_list_path(task_list) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<img id = "Logo" src = "https://cdn.discordapp.com/attachments/1071114654534860891/1208753249281249321/image.png?ex=65e46e30&is=65d1f930&hm=914efb907392d0fb407f664bc1df4503102fe12c3e6a1e04ecde05e378da2030&">

app/views/task_lists/new.html.erb
<h1>New task_list</h1>

<%= render 'form', task_list: @task_list %>

app/views/task_lists/show.html.erb
 <link rel="stylesheet" href="styles.css" />
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />


<div class="page-header">
  <%= link_to task_lists_path, class: 'btn btn-default' do %>
    All Task_lists
  <% end %>
  <%= link_to edit_task_list_path(@task_list), class: 'btn btn-primary' do %>
    Edit
  <% end %>

</div>

<h1 id ="TaskListTitle">Show Task List</h1>
<div id = "TaskList">
  
 <div class="container-fluid px-4">
 
 <div class="col-md-3">
                        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                            <div>
                                <h3 class="fs-2"><%= @task_list.price %></h3>
                                <p class="fs-5"><%= @task_list.title %></p>
                            </div>
                            <i class="fa-solid fa-bicycle fa-2xl"></i>
                        </div>
                    </div>



</div>

<img id = "Logo" src = "https://cdn.discordapp.com/attachments/1071114654534860891/1208753249281249321/image.png?ex=65e46e30&is=65d1f930&hm=914efb907392d0fb407f664bc1df4503102fe12c3e6a1e04ecde05e378da2030&">